import type { Metadata } from 'next'
import { ThemeProvider } from './context/ThemeContext'
import { ToastProvider } from './context/ToastContext'

export const metadata: Metadata = {
  title: 'Hono | nextjs',
  description: 'Generated by hono'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body>
        <ThemeProvider>
          <ToastProvider>
            {children}
          </ToastProvider>
        </ThemeProvider>
      </body>
    </html>
  )
}
